# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_auto_20161005_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
