# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_auto_20161005_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='state_abbreviation',
            new_name='state',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('High School', 'High School'), ('Associate', 'Associate'), ('BS', 'BS'), ('BA', 'BA'), ('MS', 'MS'), ('PHD', 'PHD')], default='High School', max_length=30),
        ),
    ]
