# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 22:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_app', '0005_auto_20161006_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('start_date', models.DateField(blank=True, default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='job_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='title',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='personal',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('HS', 'High School'), ('AS', 'Associate'), ('BS', 'BS'), ('BA', 'BA'), ('MS', 'MS'), ('PHD', 'PHD')], default='HS', max_length=30),
        ),
        migrations.AlterField(
            model_name='personal',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
