# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0007_personal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='form',
            field=models.CharField(default='form_', max_length=8),
        ),
    ]
