# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0009_remove_education_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
