# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0010_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(max_length=30, verbose_name='Field'),
        ),
    ]
