# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0011_auto_20161009_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True),
        ),
    ]
