# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0013_auto_20161010_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
