# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0014_personal_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
