# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0017_auto_20161010_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
