# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_app', '0020_skills_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, choices=[('programing language', 'programing language'), ('software', 'software'), ('web framework', 'web framework'), ('operating system', 'operating system'), ('tools', 'tools'), ('languages', 'languages'), ('project management', 'project management'), ('data science', 'data science'), ('database', 'database'), ('design', 'design'), ('cloud computing', 'cloud computing'), ('security', 'security')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
