# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0021_auto_20161011_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='type',
            field=models.CharField(choices=[('Traditional', 'Traditional'), ('Modern', 'Modern')], default='Modern', max_length=15),
        ),
    ]
