# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0022_education_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='school',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='degree',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='field',
            new_name='subject',
        ),
    ]
