# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0024_auto_20161013_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
